### ISSUE TITLE
로그인 시도시 플로우를 확실하게 정리하기

### ISSUE THREAD

**Issue by hongcheol** [four-art/four_artist#27]
기존에 controller에서 loginFail로 구현해놨었는데, 지금은 없어져서 그냥 에러 발생하면 화이트 라벨 뜨게해놓았음.

랜딩페이지나 에러임을 알려주는 페이지 만들고 메인으로 돌아가기 버튼을 넣거나 하는게 좋을 것 같다는 생각.

----- 여기부터는 개발 영역-----
로그인 눌렀을 때, 지금은 signup으로 넘어가는데 일단 로그인 인증 후에 이미 가입된 사람인지 판단해서 바로 메뉴로 가게하고 등록하러 가게하는 것으로 구분해야할 것 같음.

컨트롤러 영역은 적당하게 기능 명시하고 각각의 흐름에 맞게 return 등 부탁함.

**Comment by uding3866** [comment]
궁금해서 물어보는건데 그 간편로그인에서 Fail 발생하는 상황이 어떤게 있지?
비밀번호가 틀리더라도 구글,카카오 거기에서 틀리는 거라..그쪽으로 넘어가야하나

**Comment by hongcheol** [comment]
정상적인 경로로 접근하는 경우는 그렇겠지만 그냥 다이렉트로 signup 페이지로 접속하거나 그러는 경우도 대비를 해야함.

**Comment by uding3866** [comment]
으음 그러면, 그럴 경우 랜딩페이지로 넘어가면서 오버랩으로 안내문구 띄워주는 걸로.
안내문구는 "로그인을 먼저 해주세요" 이렇게?

**Comment by hongcheol** [comment]
ㅇㅇㅇ 다양한 예외가 있는데 지금 생각나는거는 
1.비정상적인 경로로 접근한 경우
2.소셜 로그인을 시도했는데 이미 있는 이메일인 경우

이에대한 처리가 필요해보임

**Comment by uding3866** [comment]
ㅇㅋ!
