### ISSUE TITLE
게시글 보여주는 페이지 구성

### ISSUE THREAD

**Issue by hongcheol** [four-art/four_artist#48]
게시글 보여주는 화면은
게시글의 정보를 가져와서 뿌리는 공간과 댓글 정보를 가져와서 뿌리는 공간으로 구분
구분한 이유는 댓글에는 게시글 작성자 이외에도 다른 유저들도 있어야하는데 이를 게시글에 포함시켜버리면 데이터 베이스를 관리하기 복잡해질 것이라 판단(<이 부분에대해서 자유롭게 의견 제시 부탁바람)
북마크에 관련된 부분 역시 따로 관리하려하는데, 다들 어떻게 생각하는지 의견 공유 부탁합니다.

**Comment by uding3866** [comment]
구분을 해도 게시글과 해당 게시글의 댓글, 북마크가 연결이 되는건가요?
따로 관리하게 되면 어떻게 되는지 잘 몰라서

**Comment by hongcheol** [comment]
구분해도 프론트단에서 화면 구성할 때, 각각의 데이터를 가져오면 됩니다. 각각은 한곳에 보여지지만 독립적으로 움직이기때문에 게시글 보여주는 화면에서 그릴 수 있습니다. 그리고 북마크는 (사용자, 글 id)로 할 예정입니다.
